CRMS/Models/Records/Appointments.cs
using CRMS.Models.Customization;
using Microsoft.Build.Framework;
using System.ComponentModel.DataAnnotations;
using RequiredAttribute = System.ComponentModel.DataAnnotations.RequiredAttribute;

namespace CRMS.Models.Records
{
    public class Appointments
    {
        public Guid Appointment_Id { get; set; } = Guid.NewGuid();

        [Required]
        public DateTime Appointment_DateTime { get; set; }

        [Required]
        [MinLength(10, ErrorMessage ="Description must be at least 10 characters long.")]
        public string Description { get; set; } = String.Empty;

        [Required]
        public SchedStatus SchedStatus { get; set; }

        [Required]
        public Guid PurposeId { get; set; }

        [Required]
        public Guid ContactId { get; set; }

        [Required]
        public DateTime CreatedDate { get; set; }

        [Required]  
        public Guid CreatedBy { get; set;}


        public Contacts? prospect { get; set; }
        public AppointmentPurpose? AppointmentPurpose { get; set; }
        public ApplicationUser? User { get; set; }


        public Appointments() { }

        public Appointments(Guid appointment_Id, DateTime appointment_DateTime, string description, SchedStatus schedStatus, Guid purposeId, Guid contactId, DateTime createdDate, Guid createdBy)
        {
            Appointment_Id = appointment_Id;
            Appointment_DateTime = appointment_DateTime;
            Description = description;
            SchedStatus = schedStatus;
            PurposeId = purposeId;
            ContactId = contactId;
            CreatedDate = createdDate;
            CreatedBy = createdBy;
        }
    }

    public enum SchedStatus
    {
        Upcoming,
        MetInPerson,
        MetOnline,
        Cancelled,
        NoShow,

    }

}

CRMS/Models/Records/Engagements..cs
using CRMS.Models.Customization;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;


namespace CRMS.Models.Records
{
    public class Engagement
    {

        public Guid Engagement_Id { get; set; } = Guid.NewGuid();

        [Required]
        [DisplayName("Engagement Date")]
        [DataType(DataType.Date)]
        //[Range(typeof(DateTime), null, DateTime.Now.ToString("yyyy-MM-dd"), ErrorMessage = "Date must not be in the future.")]
        public DateTime Engagement_Date { get; set; }


        [Required]
        [DisplayName("Topic")]
        public string Topic { get; set; }


        [Required]
        [DisplayName("Description")]
        [MaxLength(500)]
        public string? Engagement_Description { get; set; } = String.Empty;


        [Required]
        [DisplayName("Date Created")]
        public DateTime CreatedDate { get; set; } = DateTime.Now;


        [Required]
        [DisplayName("Created By")]
        public Guid CreatedById { get; set; }


        [Required]
        [DisplayName("Engagement Type")]
        public Guid ETypeId { get; set; }


        [Required]
        [DisplayName("Effectivity")]
        public Guid EffectivityId { get; set; }


        [Required]
        [DisplayName("Communications Method")]
        public Guid CommsMethodId { get; set; }


        [Required]
        [DisplayName("For Contact")]
        public Guid ContactId { get; set; }



        public ApplicationUser? User { get; set;}
        public EngagementType? EngagementType { get; set; }
        public Effectivity? Effectivity { get; set; }
        public CommunicationMethod? CommunicationMethod { get; set; }
        public Contacts? Contacts { get; set; }


        public Engagement() { } 

        public Engagement(Guid engagement_Id, DateTime engagement_Date, string topic, string? engagement_Description, DateTime createdDate, Guid createdById, Guid eTypeId, Guid effectivityId, Guid commsMethodId, Guid contactId)
        {
            Engagement_Id = engagement_Id;
            Engagement_Date = engagement_Date;
            Topic = topic;
            Engagement_Description = engagement_Description;
            CreatedDate = createdDate;
            CreatedById = createdById;
            ETypeId = eTypeId;
            EffectivityId = effectivityId;
            CommsMethodId = commsMethodId;
            ContactId = contactId;
        }
    }

}

CRMS/Models/Records/Leads.cs
using CRMS.Models.Customization;
using CRMS.Services.Records;
using System.ComponentModel.DataAnnotations;

namespace CRMS.Models.Records
{
    public class Leads
    {
        public Guid Leads_Id { get; set; } = Guid.NewGuid();

        [Required]
        public DateTime Leads_DateTime { get; set; }

        public string? PrefContactMethod { get; set; } = String.Empty;

        public string? PrefContactDay { get; set; } = String.Empty;

        public string? PrefContactTime { get; set; } = String.Empty;
        [Required]
        public DateTime CreatedDate { get; set; }

        [Required]
        public Guid ProspectId { get; set; }

        [Required]
        public Guid ProductId { get; set; }

        [Required]
        public Guid StatusId { get; set; }

        [Required]
        public Guid LeadSourceId { get; set; }

        [Required]
        public Guid CreatedBy { get; set; }

        public Contacts? prospect { get; set; }
        public LeadStatus? status { get; set; }
        public Source? source { get; set; }
        public ApplicationUser? User { get; set; }
        public Product? product { get; set; }

        public Leads() { }

        public Leads(Guid leads_Id, DateTime leads_DateTime, string? prefContactMethod, string? prefContactDay, string? prefContactTime, DateTime createdDate, Guid prospectId, Guid productId, Guid statusId, Guid leadSourceId, Guid createdBy)
        {
            Leads_Id = leads_Id;
            Leads_DateTime = leads_DateTime;
            PrefContactMethod = prefContactMethod;
            PrefContactDay = prefContactDay;
            PrefContactTime = prefContactTime;
            CreatedDate = createdDate;
            ProspectId = prospectId;
            ProductId = productId;
            StatusId = statusId;
            LeadSourceId = leadSourceId;
            CreatedBy = createdBy;
        }
    }
}

CRMS/ViewModels/Records/EngagementViewModel.cs
using CRMS.Models;
using CRMS.Models.Customization;
using CRMS.Models.Records;

namespace CRMS.ViewModels.Records
{
    public class EngagementViewModel
    {
        public Engagement? Engagement { get; set; }
        public List<EngagementType>? EngagementTypes { get; set; }
        public List<Effectivity>? Effectivities { get; set; }
        public List<CommunicationMethod>? CommunicationMethods { get; set; }
        public List<Contacts>? Contacts { get; set; }
        public List<ApplicationUser>? Users { get; set; }   


    }
}

CRMS/Controllers/LeadsController.cs
using CRMS.Data;
using CRMS.Models;
using CRMS.Models.Customization;
using CRMS.Models.Records;
using CRMS.Services;
using CRMS.Services.Contacts_Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace CRMS.Controllers
{
    public class LeadsController : Controller
    {
        private readonly IRepository<Leads> _leads;
        private readonly CRMSDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IContactRepository _contactRepo;

        public LeadsController(IRepository<Leads> leads, CRMSDbContext context, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IContactRepository contactRepo)
        {
            _leads = leads;
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            _contactRepo = contactRepo;
        }

        public async Task<IActionResult> Index()
        {
            var leadsIndex = await _leads.GetAllAsync();
            if (TempData["SuccessMessage"] != null)
            {
                ViewBag.SuccessMessage = TempData["SuccessMessage"];
            }
            if (TempData["ErrorMessage"] != null)
            {
                ViewBag.ErrorMessage = TempData["ErrorMessage"];
            }

            if (_signInManager.IsSignedIn(User))
            {
                if (User.IsInRole("Admin"))
                {
                    return View("~/Views/Records/Leads/Index.cshtml", leadsIndex);
                }
                else
                {
                    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    var myLeads = leadsIndex.Where(l => l.CreatedBy == Guid.Parse(userId));
                    return View("~/Views/Records/Leads/Index.cshtml", myLeads);
                }
            }
          
            return RedirectToAction("Index", "Home");
           
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var leadsDetails = await _leads.GetbyIdAsync(id);
            if (leadsDetails == null)
            {
                return NotFound();
            }

            return View("~/Views/Customization/Components/Purpose/AppointmentPurposes/Details.cshtml", leadsDetails);
        }

        public async Task<IActionResult> Create(Guid? Id)
        {

            ViewData["ProductId"] = new SelectList(_context.Products, "Product_Id", "ProductName");
            ViewData["StatusId"] = new SelectList(_context.Statuses, "LeadStatus_Id", "LeadStatusName");
            //ViewData["LeadSourceId"]
                if (Id == null)
                {
               
                    ViewData["LeadSourceId"] = new SelectList(_context.Sources, "Source_Id", "SourceName");
                }
                else
                {
                    var contact = await _contactRepo.GetbyIdAsync(Id ?? Guid.Empty);
                    var contactCreator = contact.ContactCreatorID;
                    if (contactCreator == null)
                    {
                        var items = _context.Sources
                       .Where(s => s.SourceName == "Company-Generated")
                       .Select(s => new SelectListItem { Text = s.SourceName, Value = s.Source_Id.ToString() })
                       .ToList();
                        ViewData["LeadSourceId"] = new SelectList(items, "Value", "Text");
                    }
                    else
                    {
                        ViewData["LeadSourceId"] = new SelectList(_context.Sources, "Source_Id", "SourceName");
                    }

                   
                }
            
            //ViewData["ProspectId"]
                if (_signInManager.IsSignedIn(User))
                {

                    if (User.IsInRole("Admin"))
                    {

                        if (Id != null)
                        {
                            var contactId = Id ?? Guid.Empty; ;
                            var contact = await _contactRepo.GetbyIdAsync(contactId);
                            ViewData["ProspectId"] = new SelectList(_context.Contacts, "Contact_Id", "FullName", contact.Contact_Id);
                        }
                        else
                        {
                            ViewData["ProspectId"] = new SelectList(_context.Contacts, "Contact_Id", "FullName");
                        }
                    }
                    else
                    {
                        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                        var userGUID = (Guid.Parse(userId));
                        if (Id != null)
                        {
                            var contactId = Id ?? Guid.Empty; ;
                            var contact = await _contactRepo.GetbyIdAsync(contactId);
                            ViewData["ProspectId"] = new SelectList(_context.Contacts.Where(e => e.ContactOwnerID == userGUID), "Contact_Id", "FullName", contact.Contact_Id);
                        }
                        else
                        {
                            ViewData["ProspectId"] = new SelectList(_context.Contacts.Where(e => e.ContactOwnerID == userGUID), "Contact_Id", "FullName");
                        }
                    }
                }
            
            return View("~/Views/Records/Leads/Create.cshtml");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Leads leadsCreate)
        {
            if (ModelState.IsValid)
            {
                leadsCreate.CreatedDate = DateTime.Now;
                var users = _userManager.GetUserId(HttpContext.User);
                leadsCreate.CreatedBy = Guid.Parse(users);
                await _leads.CreateAsync(leadsCreate);
                TempData["SuccessMessage"] = $"Congratulations! You have successfully created a new lead .";
                TempData.Keep();
                return RedirectToAction(nameof(Index));
            }
            return View("~/Views/Records/Leads/Create.cshtml", leadsCreate);
        }

        public async Task<IActionResult> Edit(Guid id )
        {
            var leadsEdit = await _leads.GetbyIdAsync(id);

            if (leadsEdit == null)
            {
                return NotFound();
            }

            var leadContactID = leadsEdit?.ProspectId;
            var LeadContact = await _contactRepo.GetbyIdAsync(leadContactID ?? Guid.Empty);
            var LeadContactOwner = LeadContact.ContactCreatorID;
            ViewData["StatusId"] = new SelectList(_context.Statuses, "LeadStatus_Id", "LeadStatusName");
            ViewData["ProductId"] = new SelectList(_context.Products, "Product_Id", "ProductName");
            //LEADSOURCE VIEW DATA
            if (LeadContactOwner != null)
            {
                ViewData["LeadSourceId"] = new SelectList(_context.Sources, "Source_Id", "SourceName");
            }
            else
            {
                var items = _context.Sources
                .Where(s => s.SourceName == "Company-Generated")
                .Select(s => new SelectListItem { Text = s.SourceName, Value = s.Source_Id.ToString() })
                .ToList();
                ViewData["LeadSourceId"] = new SelectList(items, "Value", "Text");
            }
            
            //PROSPECT ID VIEW DATA
            if (_signInManager.IsSignedIn(User))
            {
                if (User.IsInRole("Admin"))
                {
                    ViewData["ProspectId"] = new SelectList(_context.Contacts, "Contact_Id", "FullName");
                }
                else
                {
                    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    var userGUID = (Guid.Parse(userId));
                    ViewData["ProspectId"] = new SelectList(_context.Contacts.Where(e => e.ContactOwnerID == userGUID), "Contact_Id", "FullName");
                }
            }

          
            return View("~/Views/Records/Leads/Edit.cshtml", leadsEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Leads_Id, " +
            "Leads_DateTime, PrefContactMethod, PrefContactDay, PrefContactTime, CreatedDate, " +
            "ProspectId, ProductId, StatusId, LeadSourceId, CreatedBy")] Leads leadsEdit)
        {
            if (id != leadsEdit.Leads_Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _leads.UpdateAsync(leadsEdit);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecordLeadsExists(leadsEdit.Leads_Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["SuccessMessage"] = $"SUCCESS! You have successfully updated your lead's information.";
                TempData.Keep();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StatusId"] = new SelectList(_context.Statuses, "LeadStatus_Id", "LeadStatusName");
            ViewData["LeadSourceId"] = new SelectList(_context.Sources, "Source_Id", "SourceName");
            ViewData["ProspectId"] = new SelectList(_context.Contacts, "Contact_Id", "FullName");
            ViewData["ProductId"] = new SelectList(_context.Products, "Product_Id", "ProductName");
            return View("~/Views/Records/Leads/Edit.cshtml", leadsEdit);
        }

CRMS/Views/Records/Leads/Create.cshtml
@model Leads

@{
    ViewData["Title"] = "New Lead";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<header class="card1">
    <center><h1 style="font-weight: bold; font-family: Poppins; color:#002756">New Lead</h1></center>
    <hr />
    <p style="color: gray">Leads > Create</p>
    <br/>
    <form class="row g-3 needs-validation" style=" border: 2px solid lightgray;
    border-radius: 20px; padding: 35px;" novalidate asp-controller="Leads" asp-action="Create" method="post">

        <div class="col-md-6">
            <div class="form-floating">
                @Html.EditorFor(m => m.Leads_DateTime, new { htmlAttributes = new { @class = "form-control", @type = "date", @max = DateTime.Now.ToString("yyyy-MM-dd"), @required = "required" } })
                @*<input asp-for="Leads_DateTime" class="form-control" required>*@
                <label asp-for="Leads_DateTime">Lead Schedule</label>
                <span asp-validation-for="Leads_DateTime" class="text-danger"></span>
                <div class="invalid-feedback">
                    Date and Time are required!
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-floating">
                @Html.DropDownListFor(model => model.ProspectId, (IEnumerable<SelectListItem>)ViewBag.ProspectId, "-- Select Contact--", new { @class = "form-control", @required = "required"  })
                <label asp-for="ProspectId">Contact</label>
                <span asp-validation-for="ProspectId" class="text-danger"></span>
                <div class="invalid-feedback">
                    Please choose a Contact!
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-floating">
                <input asp-for="PrefContactMethod" class="form-control" placeholder=" " required>
                <label asp-for="PrefContactMethod">Preferred Contact Method</label>
                <span asp-validation-for="PrefContactMethod" class="text-danger"></span>
                <div class="invalid-feedback">
                    Preference is required!
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-floating">
                <input asp-for="PrefContactDay" class="form-control" placeholder=" " required>
                <label asp-for="PrefContactDay">Preferred Contact Day</label>
                <span asp-validation-for="PrefContactDay" class="text-danger"></span>
                <div class="invalid-feedback">
                    Preference is required!
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-floating">
                <input asp-for="PrefContactTime" class="form-control" placeholder=" " required>
                <label asp-for="PrefContactTime">Preferred Contact Time</label>
                <span asp-validation-for="PrefContactTime" class="text-danger"></span>
                <div class="invalid-feedback">
                    Preference is required!
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-floating">
                @Html.DropDownListFor(model => model.StatusId, (IEnumerable<SelectListItem>)ViewBag.StatusId, "-- Select Status --", new { @class = "form-control", @required = "required"  })
                <label asp-for="StatusId">Status</label>
                <span asp-validation-for="StatusId" class="text-danger"></span>
                <div class="invalid-feedback">
                    Please choose a Status!
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-floating">
                @Html.DropDownListFor(model => model.LeadSourceId, (IEnumerable<SelectListItem>)ViewBag.LeadSourceId, "-- Select Lead Source --", new { @class = "form-control", @required = "required"  })
                <label asp-for="LeadSourceId">Lead Source</label>
                <span asp-validation-for="LeadSourceId" class="text-danger"></span>
                <div class="invalid-feedback">
                    Please choose a Lead Source!
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-floating">
                @Html.DropDownListFor(model => model.ProductId, (IEnumerable<SelectListItem>)ViewBag.ProductId, "-- Select Product --", new { @class = "form-control", @required = "required"  })
                <label asp-for="ProductId">Product</label>
                <span asp-validation-for="ProductId" class="text-danger"></span>
                <div class="invalid-feedback">
                    Please choose a Purpose!
                </div>
            </div>
        </div>

        <div class="col-12">
            <br />
            <button type="submit" class="btn w3-highway-blue">Create</button>
            <button onclick="history.go(-1)" class="btn btn-secondary">Cancel</button>
        </div>

    </form>
</header>


<script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
        'use strict'

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.querySelectorAll('.needs-validation')

        // Loop over them and prevent submission
        Array.prototype.slice.call(forms)
            .forEach(function (form) {
                form.addEventListener('submit', function (event) {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }

                    form.classList.add('was-validated')
                }, false)
            })
    })()

</script>

CRMS/Views/Records/Leads/Delete.cshtml
@model Leads

<div class="w3-container d-flex justify-content-center align-items-center">
    <div class="w3-container ">
        <form class="w3-container " asp-controller="Leads" asp-action="Delete">
            <input type="hidden" asp-for="Leads_Id" />
            <div class="card1" style="max-width:600px">
                <div class="w3-container  w3-padding-16 ">
                    <h3 class="w3-center">Are you sure you want to delete this lead record?</h3>
                    
                    <button type="submit" value="DELETE" class="btn btn-danger w3-right">DELETE</button>
                    <button asp-action="index" class="btn btn-secondary">Cancel</button>
                </div>
            </div>
        </form>
    </div>
</div>

CRMS/Views/Records/Leads/Edit.cshtml
@model Leads

@{
    ViewData["Title"] = "Edit Lead";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<header class="card1">
    <center><h1 style="font-weight: bold; font-family: Poppins; color:#002756">Edit Lead</h1></center>
    <hr />
    <p style="color: gray">Leads > Edit</p>
    <br />
    <form class="row g-3 needs-validation" style=" border: 2px solid lightgray;
    border-radius: 20px; padding: 35px;" novalidate asp-controller="Leads" asp-action="Edit" method="post">
            <input type="hidden" asp-for="Leads_Id" />
            <input type="hidden" asp-for="CreatedBy" />
            <input type="hidden" asp-for="CreatedDate" />

        <div class="col-md-6">
            <div class="form-floating">
                @Html.EditorFor(m => m.Leads_DateTime, new { htmlAttributes = new { @class = "form-control", @type = "date", @max = DateTime.Now.ToString("yyyy-MM-dd"), @required = "required" } })
                <label asp-for="Leads_DateTime">Creation Date</label>
                <span asp-validation-for="Leads_DateTime" class="text-danger"></span>
                <div class="invalid-feedback">
                    Date and Time are required!
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-floating">
                @Html.DropDownListFor(model => model.ProspectId, (IEnumerable<SelectListItem>)ViewBag.ProspectId, "-- Select Contact--", new { @class = "form-control", @required = "required"  })
                <label asp-for="ProspectId">Contact</label>
                <span asp-validation-for="ProspectId" class="text-danger"></span>
                <div class="invalid-feedback">
                    Please choose a Contact!
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-floating">
                <input asp-for="PrefContactMethod" class="form-control" placeholder=" " required>
                <label asp-for="PrefContactMethod">Preferred Contact Method</label>
                <span asp-validation-for="PrefContactMethod" class="text-danger"></span>
                <div class="invalid-feedback">
                    Preference is required!
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-floating">
                <input asp-for="PrefContactDay" class="form-control" placeholder=" " required>
                <label asp-for="PrefContactDay">Preferred Contact Day</label>
                <span asp-validation-for="PrefContactDay" class="text-danger"></span>
                <div class="invalid-feedback">
                    Preference is required!
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-floating">
                <input asp-for="PrefContactTime" class="form-control" placeholder=" " required>
                <label asp-for="PrefContactTime">Preferred Contact Time</label>
                <span asp-validation-for="PrefContactTime" class="text-danger"></span>
                <div class="invalid-feedback">
                    Preference is required!
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-floating">
                @Html.DropDownListFor(model => model.StatusId, (IEnumerable<SelectListItem>)ViewBag.StatusId, "-- Select Status --", new { @class = "form-control", @required = "required"  })
                <label asp-for="StatusId">Status</label>
                <span asp-validation-for="StatusId" class="text-danger"></span>
                <div class="invalid-feedback">
                    Please choose a Status!
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-floating">
                @Html.DropDownListFor(model => model.LeadSourceId, (IEnumerable<SelectListItem>)ViewBag.LeadSourceId, "-- Select Lead Source --", new { @class = "form-control", @required = "required"  })
                <label asp-for="LeadSourceId">Lead Source</label>
                <span asp-validation-for="LeadSourceId" class="text-danger"></span>
                <div class="invalid-feedback">
                    Please choose a Lead Source!
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-floating">
                @Html.DropDownListFor(model => model.ProductId, (IEnumerable<SelectListItem>)ViewBag.ProductId, "-- Select Product --", new { @class = "form-control", @required = "required"  })
                <label asp-for="ProductId">Product</label>
                <span asp-validation-for="ProductId" class="text-danger"></span>
                <div class="invalid-feedback">
                    Please choose a Purpose!
                </div>
            </div>
        </div>

        <div class="col-12">
            <br />
            <button type="submit" class="btn btn-primary">Edit</button>
            <button onclick="history.go(-1)" class="btn btn-secondary">Cancel</button>
        </div>

    </form>
</header>

@section Scripts{
<script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
        'use strict'

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.querySelectorAll('.needs-validation')

        // Loop over them and prevent submission
        Array.prototype.slice.call(forms)
            .forEach(function (form) {
                form.addEventListener('submit', function (event) {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }

                    form.classList.add('was-validated')
                }, false)
            })
    })()

</script>
<script>
    function goBack() {
        window.history.back();
    }
</script>
}